#!/usr/bin/env bash

SND_HOME=${SND_HOME:-"$HOME/Nextcloud/sync/snd"}
PLAY__5S="Alt+1"
PLAY_10S="Alt+2"
PLAY_30S="Alt+3"
STOP_KEY="Control+c"

snd="$(find "$SND_HOME" -type f -printf '%f\n' | \
    sort -nr | \
    rofi -i -mesg "Select file. ${STOP_KEY} to stop\\nTest" \
        -dmenu \
        -kb-custom-1  "${PLAY__5S}" \
        -kb-custom-2  "${PLAY_10S}" \
        -kb-custom-3  "${PLAY_30S}" \
        -kb-custom-10 "${STOP_KEY}" \
        -p "play: ")"
rofi_exit=$?

if [[ $rofi_exit -eq 0 ]]; then
    cvlc "$SND_HOME/$snd" &
elif [[ $rofi_exit -eq 20 ]]; then
    pkill -f "vlc .* $SND_HOME"
elif [[ $rofi_exit -eq 10 ]]; then
    timeout 5 cvlc "$SND_HOME/$snd" &
elif [[ $rofi_exit -eq 11 ]]; then
    timeout 10 cvlc "$SND_HOME/$snd" &
elif [[ $rofi_exit -eq 12 ]]; then
    timeout 30 cvlc "$SND_HOME/$snd" &
else
    exit
fi
